### ISSUE TITLE
text to bitmap issues

### ISSUE THREAD

**Issue by idavydov** [gfwilliams/Gadgetbridge#3]
#### Before reporting a bug, please confirm the following:
- [x] I have read the [wiki](https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://codeberg.org/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [Codeberg Terms of Use](https://codeberg.org/codeberg/org/src/branch/master/TermsOfUse.md)

### I got Gadgetbridge from:
* [x] Play store beta

#### Your issue is:
I'm having two issues when **text to bitmap is enabled** and **transliteration is disabled**.

##### Poor image rendering
If I use gadgedbridge debug to send a simple notification in Cyrillic "тест", I get font rendering problems.

![PXL_20220610_145414575](https://user-images.githubusercontent.com/671660/173094690-b41c691e-2134-4de9-b106-b35cd7a8cf35.jpg)

##### When a Cyrillic notification comes from signal messenger, I just get an empty screen without any buttons. Only widgets are visible.
Please let me know if I should make is a separate issue.

#### Your wearable device is:
Bangle.js 2v13

#### Your Android version/manufacturer flavor is:
Google Pixel 6

#### Your Gadgetbridge version is:
0.67.1a-banglejs
6fb22b944132f27bf54d0af00d165069160f9754

**Comment by gfwilliams** [comment]
Fixed with c2d98b5a24d069f1f1299413bf38d969a7943858

It was actually just `"\0"+"0" => "\00"` (which is wrong)

**Comment by idavydov** [comment]
Thanks, @gfwilliams ! I can confirm that it works now.
