### ISSUE TITLE
NullPointerException on HTTP call

### ISSUE THREAD

**Issue by ghost** [gfwilliams/Gadgetbridge#7]
Here is what I got in the Gadgetbridge log when I try to call a https site

`22:30:50.470 [Binder:6134_8] INFO  n.f.g.s.d.b.BangleJSDeviceSupport - UART RX LINE: {"t":"http","url":"https://pur3.co.uk/hello.txt","id":"40699574509"}
22:30:50.470 [Binder:6134_8] INFO  n.f.g.s.d.b.BangleJSDeviceSupport - UART RX JSON parsed successfully
22:30:50.495 [main] INFO  n.f.g.s.d.b.BangleJSDeviceSupport - UART TX: GB({t:"http",id:"40699574509",err:"com.android.volley.VolleyError: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Set java.util.Map.keySet()' on a null object reference"})`

I am using the following snipped:
`	Bangle.http("https://pur3.co.uk/hello.txt").then(data=>{
    E.showMessage(data);
  });`

Version of Gadgetbridge: 0.68.0b-banglejs
Version of Bangle 2: 2v15.5

**Comment by gfwilliams** [comment]
As mentioned in your forum post at http://forum.espruino.com/conversations/370708/?offset=100#comment16673484

Do you think this could be http://forum.espruino.com/conversations/379050/ ? 

If so it's already fixed (in the nightly builds) but I haven't yet done a release with it in

**Comment by rullen** [comment]
Yes indeed, it worked when I tested to add the headers-part

**Comment by ghost** [comment]
Yes indeed, it worked when I tested to add the headers-part

**Comment by gfwilliams** [comment]
Ok, great - then I think this is fixed, it's just that I need to push an update to the Play Store
